### ISSUE TITLE
[TASK] Add additional documentation

### ISSUE THREAD

**Issue by dutterbutter** [webb-tools/relayer#113]
# Overview
We need to continue to improve the documentation of the relayer repo. 

### Tasks

- [ ] Add documentation / illustration of lifetime proposals
- [ ] Include testing instructions on the README.md
- [ ] Document and provide usage example for API's (e.g. data querying)
- [ ] Include instructions for setting up the Relayer for various network/contracts (e.g. evm, substrate)
- [ ] Add Contributing.md for external contributors 
- [ ] Update external v2 docs with the above documentation and hosted setup
