### ISSUE TITLE
[CHECKLIST] VAnchor Integration

### ISSUE THREAD

**Issue by dutterbutter** [webb-tools/relayer#122]
## Overview

This checklists intends to outline the tasks to fully integrate and support the VAnchor. 

### Tasks

- [x] https://github.com/webb-tools/relayer/issues/88
- [x] https://github.com/webb-tools/relayer/issues/89
- [x] https://github.com/webb-tools/relayer/issues/90
- [x] https://github.com/webb-tools/relayer/issues/91
- [x] https://github.com/webb-tools/relayer/issues/63
- [x] https://github.com/webb-tools/relayer/issues/66
