### ISSUE TITLE
[CHECKLIST] Anchor EVM integration

### ISSUE THREAD

**Issue by dutterbutter** [webb-tools/relayer#124]
## Overview

The purpose of this checklist is to outline the tasks required to support EVM anchor in the relayer.

### Tasks

- [x] https://github.com/webb-tools/relayer/issues/120
- [ ] https://github.com/webb-tools/relayer/issues/116
- [x] #131
- [x] #132
- [x] https://github.com/webb-tools/relayer/issues/115
