### ISSUE TITLE
[CHECKLIST] Relayer Testing

### ISSUE THREAD

**Issue by dutterbutter** [webb-tools/relayer#130]
## Overview

Tracking checklist of Relayer testing tasks. 

**Tasks:**

- [x] https://github.com/webb-tools/relayer/issues/126
- [x] https://github.com/webb-tools/relayer/issues/127
- [x] https://github.com/webb-tools/relayer/issues/125
- [x] https://github.com/webb-tools/relayer/issues/90
- [x] https://github.com/webb-tools/relayer/issues/131
- [x] https://github.com/webb-tools/relayer/issues/132
