### ISSUE TITLE
[CHECKLIST] Add support for Eggnet Runtime

### ISSUE THREAD

**Issue by dutterbutter** [webb-tools/relayer#163]
## Overview

Need to add support for Eggnet runtime. 

### Deliverables

- [ ] [TASK] Watching for signed proposals
- [ ] [TASK] Watching for dkg changes (public key changes, and updating SignatureBridge)
- [ ] [TASK] Add support for Anchor and Mixer leaf watcher pallets 
- [ ] [TASK] Support tx relaying (mixer, anchor, vanchor)
