### ISSUE TITLE
[Task] Code clean up 

### ISSUE THREAD

**Issue by salman01zp** [webb-tools/relayer#201]
## Task Checklist
- [x] Create separate folder for dkg event watchers ` path:/event_watcher/dkg` 
- [x] Add evm `signature_bridge_watcher` to `path:/event_watcher/evm/`
- [x] Remove `proposal_signing_backend` from event_watcher folder
