### ISSUE TITLE
[Task] Update tests for relayer services using V-Anchor deposits

### ISSUE THREAD

**Issue by salman01zp** [webb-tools/relayer#233]
## Task Summary
Since fixed anchor is deprecated, update relayer services tests using V-Anchor

### Update tests
- [ ] Data querying service
- [ ] Governance relay service
- [x]  Private Tx relay service

**Comment by salman01zp** [comment]
updated in #261
