### ISSUE TITLE
[SPEC] Use dynamic queries  for substrate transaction calls

### ISSUE THREAD

**Issue by salman01zp** [webb-tools/relayer#274]
## Overview

Earlier it was challenging to pass the `SubmittableExtrinsic` type call to the `TransactionQueue` and so we decided to give just call-data to the queue and then construct SubmittableExtrinsic type after dequeuing it from TransactionQueue. To do this we had to construct `additional_and_extra_params`, `signature`,  `Encode extrinsic` manually.

```rust
// 1.Construct our custom additional/extra params.
let additional_and_extra_params = {
    // Obtain spec version and transaction version from the runtime version of the client.
    let runtime = client
        .rpc()
        .runtime_version(None)
        .map_err(Into::into)
        .map_err(backoff::Error::transient)
        .await?;
    X::new(
        runtime.spec_version,
        runtime.transaction_version,
        account_nonce,
        *client.genesis(),
        Default::default(),
    )
};

// 2. Construct signature. This is compatible with the Encode impl
//    for SignedPayload (which is this payload of bytes that we'd like)
//    to sign. See:
//    https://github.com/paritytech/substrate/blob/9a6d706d8db00abb6ba183839ec98ecd9924b1f8/primitives/runtime/src/generic/unchecked_extrinsic.rs#L215)
let signature = {
    let mut bytes = Vec::new();
    call_data.encode_to(&mut bytes);
    additional_and_extra_params.encode_extra_to(&mut bytes);
    additional_and_extra_params
        .encode_additional_to(&mut bytes);
    if bytes.len() > 256 {
        signer.sign(&blake2_256(&bytes))
    } else {
        signer.sign(&bytes)
    }
};

// 3. Encode extrinsic, now that we have the parts we need. This is compatible
//    with the Encode impl for UncheckedExtrinsic (protocol version 4).
let extrinsic = {
    let mut encoded_inner = Vec::new();
    .
    .
    encoded.extend(encoded_inner);
    encoded
};
// encoded extinsic
let encoded_extrinsic = subxt::Encoded(extrinsic);
```

## Subxt dynamic queries

With an introduction to dynamic queries, it became easier to construct, save, and execute transaction calls later through TransactionQueue.
- Enqueue transaction call into the queue. It is done by signature-bridge-watchers
  ```rust
    let dynamic_tx_payload = subxt::dynamic::tx(
            "SignatureBridge",
            "execute_proposal",
            vec![
                Value::u128(typed_chain_id.chain_id() as u128),
                Value::from_bytes(parsed_proposal_bytes),
                Value::from_bytes(proposal_data),
                Value::from_bytes(signature),
            ],
        );
   let data_hash = utils::keccak256(&encoded_call);
   let tx_key = SledQueueKey::from_substrate_with_custom_key(
       chain_id,
       make_execute_proposal_key(data_hash),
       );
   QueueStore::<Vec<u8>>::enqueue_item(&store, tx_key, dynamic_tx_payload)?;
   tracing::debug!(
       data_hash = ?hex::encode(data_hash),
       "Enqueued execute-proposal tx",
      );
    
  ```
- Substrate TrasanctionQueue
   In transaction queue we will dequeue tx_payload of type [DynamicTxPayload](https://docs.rs/subxt/latest/subxt/tx/struct.DynamicTxPayload.html#) and execute using OnlineClinet
   ```rust
    let api = subxt::client::OnlineClient::<ProtocolSubstrateConfig>::new()
               .await?;
     // dequeue transaction payload. This are call params stored as bytes
     let tx_payload = store.dequeue_item(
             SledQueueKey::from_substrate_chain_id(chain_id),
              )?;
     let hash = api.tx().sign_and_submit_then_watch_default(&tx_payload, &signer)

   ```
- Replace subxt::Client with subxt::client::OnlineClient
Release [notes](https://github.com/paritytech/subxt/releases) more details on dynamic queries 

## Task Checklist
- [x]  Update subxt on webb-rs to v0.24 [#PR-94](https://github.com/webb-tools/webb-rs/pull/94)
- [x] Update subxt changes on relayer
- [x] Use dynamic query for executing transaction call through TrsanctionQueue
