### ISSUE TITLE
[TASK] Migrate from warp to axum web-framework

### ISSUE THREAD

**Issue by shekohex** [webb-tools/relayer#333]
### Overview

After doing a simple research on the current Rust web framewroks, turns out that [axum](https://github.com/tokio-rs/axum) looks a good fit for us.

### Task Checklist

Migrate all these endpoints:

- [ ] `/api/v1/info`
- [ ] `api/v1/ip`
- [ ] `api/v1/leaves/evm`
- [ ] `api/v1/leaves/substrate`
- [ ] `api/v1/encrypted_outputs/evm`
- [ ] `api/v1/encrypted_outputs/substrate`
- [ ] `api/v1/metrics`
- [ ] `api/v1/metrics/evm`
- [ ] `api/v1/metrics/substrate`
- [ ] `api/v1/ws` (Websocket)
