### ISSUE TITLE
[TASK] Calculate estimated fee for substrate based transactions

### ISSUE THREAD

**Issue by salman01zp** [webb-tools/relayer#364]
## Overview
Calculate the estimated fee for relaying substrate based transactions/extrinsic. Fees on substrate based chains are calculated based on three parameters
- Base Fee
- Length Fee
- Network congestion

You can read more about fee details [here](https://wiki.polkadot.network/docs/learn-transaction-fees) 

Here is an open issue on subxt [Return fee details for an Extrinsic #527](https://github.com/paritytech/subxt/issues/527)

-----
### Task Checklist
Similar to EVM Fees Enpoint, we will need one for Substrate.

- [ ] Add an API endpoint that takes in the (TypedChainId, VAnchorTreeId, estimatedXtFees) and returns the relayer estimated fees.
- [ ] Calculate the estimated fee for relaying transaction (see below for the calculation)
- [ ] Add validation check for fee submitted by a user.
- [ ] Write tests to ensure that the above functionality works correctly

### Estimate the Extrinsic fees

There is an RPC method that you can call with the signed extrinsic call and it will return the fees details, this RPC is `payment_queryFeeDetails`. Here is an example:

* Request Payload:
```json
{"id":1,"jsonrpc":"2.0","method":"payment_queryInfo","params":["0xad0184008eaf04151687736326c9fea17e25fc5287613693c912909cb226aa4794f26a48010101010101010101010101010101010101010101010101010101010101010101010101010101010101010101010101010101010101010101010101010101010124010000000004306d000000"]}
```
* Response:

```json
{"jsonrpc":"2.0","result":{"weight":1307595,"class":"normal","partialFee":"1130000000100090506"},"id":1}
```

On the client side, the user will use this method to estimate the fees so they can send to the relayer. 

You will notice the following information in the result:

```js
partialFee = "1130000000100090506";
```

The final fee is like the following:
```js
// Calculates the fees in how much tokens
fee = parseInt(partialFee) / (10 ** tokenDecimals)
```

Example:
```js
tokenDecimals = 18; // for tTNT (Tangle Standalone Test Network)
partialFee = "1130000000100090506";
fee = parseInt(partialFee) / (10 ** tokenDecimals) // => 1.1300 tTNT

// The calculated fees above, is the base transaction fees that the relayer will pay for sending this transaction.
```

If you are using polkadot API, you can see the docs [here](https://polkadot.js.org/docs/api/cookbook/tx#how-do-i-estimate-the-transaction-fees) about estimating the transaction fees.

### Wrapped Token to the Native token Conversion

When working on the VAnchors, we are working on wrapped tokens, each VAnchor as an associated `assetId` that can be later used to get that asset information, for example say we have `assetId = 1`, by calling `assetRegistry.assets` we will get the following:
```
{
  name: webbtTNT
  assetType: PoolShare
  existentialDeposit: 100,000,000,000,000,000
  locked: false
}
```

You will notice the `name` is `webbtTNT` and it is a wrapped token over the native `tTNT` token, so it should be `1:1` conversion in this case.

> Please Notice that since currently there is no way for us to fetch prices of Substrate tokens, we will (for now) hardcode the price of the `1 tTNT = $0.10`. That also could change in the future.

**Comment by shekohex** [comment]
Related to https://github.com/webb-tools/tangle/issues/151
