### ISSUE TITLE
[TASK] Deploy relayer with fee, refund and DKG backend for standalone node

### ISSUE THREAD

**Issue by shekohex** [webb-tools/relayer#380]
### Overview

Deploy Relayer 2 with the latest release that also supports the new Fee system and Refund, in addition to that, the deployed relayer should also use the Tangle Standalone node as signing backend.

Token: `webbtTNT-standalone`

### Task Checklist

- [x] Update Relayer 2 with the latest relayer release.
- [x] Deploy a new bridges on 7 different testnets (leaving 1 slot for Tangle Standalone itself)
- [x] Configure the Relayer 2 to use the new deployment of smart contracts
- [x] Configure the relayer to use the Tangle Standalone network
- [x] Transfer the ownership of the governor to the DKG.
- [x] Configure the relayer to use the Tangle Standalone network as DKG Signing backend.
- [x] Update the dApp team with the changes.
- [x] Live testing of the new deployment using the dApp.

**Comment by shekohex** [comment]
Hey @salman01zp !
Could you please after finishing the deployment, add a comment here to that Task with the new deployment information?

Would be also good to include these config files we are using in the deployed Relayer and add it under `config/deployment/tangle-standalone`.

**Comment by salman01zp** [comment]
Made new deployment for `webbtTNT-standalone`

### (EVMs) Create2 Anchor and SignatureBridge Addresses

- Anchor - `0xf8c9d24e3bc3e2d3eddde507079b08e82f239fc4`
- SignatureBridge - `0xbd7cddd8a179beb18bed999fd0d3b4d9ddcf3bef`
- FungibleTokenWrapper - `0x13f2609cffbcf47e3c403a850fd40522904a64f0`

You can refer this [notion](https://www.notion.so/hicommonwealth/Bridge-Deployments-54496ac2c29d4a7f9867bb9fa3ed1b2a?pvs=4#908560a09a704838931f61b87ae070f7) doc more details

**Comment by shekohex** [comment]
Cool, will close this issue once we finish all the tasks in the main issue comment.
