### ISSUE TITLE
[TASK] Deploy relayer with fee, refund and DKG backend for parachain node

### ISSUE THREAD

**Issue by shekohex** [webb-tools/relayer#381]
### Overview

Deploy Relayer 3 with the latest release that also supports the new Fee system and Refund, in addition to that, the deployed relayer should also use the Tangle Parachain node as signing backend.

### Task Checklist

- [x] Update Relayer 3 with the latest relayer release.
- [x] Deploy a new bridges on 7 different testnets (leaving 1 slot for Tangle Parachain itself)
- [x] Configure the Relayer 3 to use the new deployment of smart contracts
- [x] Configure the relayer to use the Tangle Parachain network
- [ ] Transfer the ownership of the governor to the DKG.
- [x] Configure the relayer to use the Tangle Parachain network as DKG Signing backend.
- [ ] Update the dApp team with the changes.
- [ ] Live testing of the new deployment using the dApp.

**Comment by shekohex** [comment]
Hey @salman01zp !
Could you please after finishing the deployment, add a comment here to that Task with the new deployment information?

Would be also good to include these config files we are using in the deployed Relayer and add it under `config/deployment/tangle-parachain`
