### ISSUE TITLE
[TASK] Add more clippy checks to the CI to avoid runtime crashes

### ISSUE THREAD

**Issue by shekohex** [webb-tools/relayer#383]
### Overview

In our effort to make our relayer system more stable, we are working to detect and remove any possible runtime crashes due to the use of `unwrap` or `expect` or any other means of panicking during the runtime instead of just handling the error gracefully.

### Task Checklist

- [x] Add Clippy Checks to the CI similar to this one [here](https://github.com/LemmyNet/lemmy/blob/fdaa2bcf090c3fb1c2c38fe7bac8026ce67457d3/scripts/fix-clippy.sh#L8-L21)
- [x] Make sure that CI creates the warning and comments on the PR by using https://github.com/actions-rs/clippy-check
- [x] Update and Fix any clippy warnings in the same PR.

**Comment by shekohex** [comment]
Closed by #408
