### ISSUE TITLE
[TASK] Link Tangle Standalone to the Standalone Bridge deployment

### ISSUE THREAD

**Issue by shekohex** [webb-tools/relayer#384]
### Overview

After finishing the #380 Task, we should create a VAnchor on the Tangle Standalone Network then link these as a new edge to the corresponding deployment.

### Task Checklist

- [x] Register `webbtTNT` asset on Tangle Standalone
- [x] Create a token pool using this asset and the native asset.
- [x] Create a new VAnchor that would utilize this token.
- [x] Link that VAnchor to the current Standalone deployment.
- [x] Test the deployment by doing same-chain transact call.
- [ ] Test the deployment by making a cross-chain-cross-system transact call (EVM <=> Substrate)
