### ISSUE TITLE
[TASK] Link Tangle Parachain to the Parachain Bridge deployment

### ISSUE THREAD

**Issue by shekohex** [webb-tools/relayer#385]
### Overview

After finishing the #381 Task, we should create a VAnchor on the Tangle Parachain Network then link these as a new edge to the corresponding deployment.

### Task Checklist

- [ ] Register `webbParachain` asset on Tangle Parachain
- [ ] Create a token pool using this asset and the native asset.
- [ ] Create a new VAnchor that would utilize this token.
- [ ] Link that VAnchor to the current Parachain deployment.
- [ ] Test the deployment by doing same-chain transact call.
- [ ] Test the deployment by making a cross-chain-cross-system transact call (EVM <=> Substrate)
