### ISSUE TITLE
[TASK] Split the service.rs file into smaller modules by the system

### ISSUE THREAD

**Issue by shekohex** [webb-tools/relayer#386]
### Overview

In our effort for making our codebase more readable and approachable by new developers, we should start refactoring big modules into smaller related and contained modules, and we will start by [`service.rs`](https://github.com/webb-tools/relayer/blob/fe750d39ae8614be15fb9e7882f2ee96b731fa1c/services/webb-relayer/src/service.rs) file.

### Task Checklist

Before working on this task, take one step back to identify which parts that needs to be refactored or moved to new modules.

- [x] Split the file into smaller modules by system (evm, substrate, ..etc)
- [x] Move evm related logic to the evm submodule
- [x] Move substrate related logic to the substrate submodule
- [ ] Move mocked implementation into separate integration_tests submodule.
- [x] Update documentation
- [x] Update tests (if needed)

**Comment by Nutomic** [comment]
It would also be nice if we could move mock related functionality into an [integration test](https://doc.rust-lang.org/book/ch11-03-test-organization.html#integration-tests). That way we could exclude mock code from clippy which should make #383 easier.

**Comment by Nutomic** [comment]
It would also be nice if we could move mock related functionality into an [integration test](https://doc.rust-lang.org/book/ch11-03-test-organization.html#integration-tests). That way we could exclude mock code from clippy which should make #383 easier.

**Comment by shekohex** [comment]
> It would also be nice if we could move mock related functionality into an [integration test](https://doc.rust-lang.org/book/ch11-03-test-organization.html#integration-tests). That way we could exclude mock code from clippy which should make #383 easier.

Good idea, will update the task with your recommended changes.
