### ISSUE TITLE
[TASK] Create a Grafana dashboard utilizing the relayer metrics

### ISSUE THREAD

**Issue by shekohex** [webb-tools/relayer#388]
### Overview

After working on #387, we should work on a Metrics Dashboard for better understanding how the relayer performs and the other areas where we collect metrics, we need a simple way to visualize these metrics; so that we would make use of https://grafana.com/ dashboards.

### Task Checklist

- [x] Run Grafana locally (using docker if possible)
- [x] Run the relayer locally with Local EVM network setup + Local Tangle Standalone
- [ ] Start using the relayer locally by sending some transactions (_optional_)
- [ ] Integrate the Relayer metrics into the grafana dashboard.
- [ ] Create a dashboard that shows _all_ the supported metrics that are exported by the relayer.
- [x] Export the dashboard for future usage.

**Comment by Nutomic** [comment]
First steps are finished, there is now a working Prometheus/Grafan setup which shows a single metric as demonstration. Next step is to build the actual dashboard. You say that it should show *all* supported metrics but that is pretty vague. Is there maybe an existing Grafana dashboard for a similar project that I could use as reference?

**Comment by shekohex** [comment]
> First steps are finished, there is now a working Prometheus/Grafan setup which shows a single metric as demonstration. Next step is to build the actual dashboard. You say that it should show _all_ supported metrics but that is pretty vague. Is there maybe an existing Grafana dashboard for a similar project that I could use as reference?

If it is a chore task, we can allocate someone else to do it, but for now showing an example is good.

**Comment by shekohex** [comment]
Closed by #413
