### ISSUE TITLE
[TASK] Improve the docs for the internal Queue system for the relayer

### ISSUE THREAD

**Issue by shekohex** [webb-tools/relayer#390]
### Overview

In our effort for making our codebase more readable and approachable by new developers, we should start documenting and creating flow-charts of different internal system and structures used by the relayer itself, for better understanding and easier onboarding of new developers. And for that we will start by documenting our internal Queue system and the message passing system. 

### Task Checklist

- [ ] Create a flow diagram to visualize how the Internal Queue Systems working
- [ ] Create a flow diagram to show how the interaction between the events handlers with each other using the queue system
- [ ] Create a doc file to use the above diagrams with a simplified version of our system.
- [ ] add a small rust test to ensure our docs are up-to-date when we change anything in how that mechanism works.
