### ISSUE TITLE
[CHECKLIST] Relayer Unit Testing in Rust

### ISSUE THREAD

**Issue by shekohex** [webb-tools/relayer#391]
### Overview

To improve the relayer testing and code coverage, we are aiming to write all of our tests in Rust, that would allow us for writing separate and small unit tests + faster integration tests.

This a checklist of different small tasks that should be done to achieve that goal. 

### Checklist

- [ ] [TASK] Add a way to create a `LocalEvmChain` using Anvil
- [ ] [TASK] Add method to the `LocalEvmChain` to deploy `ERC20Token` Contract
- [ ] [TASK] Add method to the `LocalEvmChain` to deploy `Treasury` Contract
- [ ] [TASK] Add method to the `LocalEvmChain` to deploy `PoseidonHasher` Contract
- [ ] [TASK] Add method to the `LocalEvmChain` to deploy `SignatureBridge` Contract
- [ ] [TASK] Add method to the `LocalEvmChain` to deploy `VAnchor` Contract
- [ ] [TASK] Add a way to save and load the EVM Chain state for faster testing
