### ISSUE TITLE
[TASK] Remove the hardcoded `NativeToken` names while fetching prices

### ISSUE THREAD

**Issue by shekohex** [webb-tools/relayer#412]
### Overview

Instead of Hard-coding chain native token names in the relayer, we should instead use something like 

```
https://chainid.network/chains.json
```

Which contains a big list of networks/chains, each has a `chainId`, a `name` and `nativeCurrency` with its `symbol` and decimals too!

We should make use of that and bundle this file with the relayer binary, no need to fetch it every time.

### Coingecko-Specific Token Ids

Coingecko uses it's own set of token ids, different than just using the token symbol or ticker, hence, the generated chains.json file should include somehow the corresponding coingecko token id by query the 
```
https://api.coingecko.com/api/v3/coins/list?include_platform=false
```
endpoint which contains the `id`, `symbol` and `name`.

The result `chains.json` file should include the minimum information needed by the relayer, for now the `ChainInfo` struct may look like the following:

```rust
struct ChainInfo {
    pub name: String,
    pub short_name: String,
    pub chain_id: u32,
    pub native_currency: ChainNativeCurrency,
}

struct ChainNativeCurrency {
    pub name: String,
    pub symbol: String,
    pub decimals: u8,
   pub coingecko_token_id: Option<String>,
}
```

### Task Checklist

- [x] Add `chains.json` in the repos fixtures
- [x] Include the Chains in the relayer binary (e.g by using `include_str!` macro)
- [x] Create a simple representation of `Chain` that contains the min info we need from that JSON file
- [x] Parse and store the chains as a map between `TypedChainId` to `ChainInfo` and add it to the relayer context.
- [x] Make use of the chains to fetch the native token name and the decimals while calculating the fees.
