### ISSUE TITLE
[TASK] Process DKG/Substrate extrinsic calls  through Tx queue

### ISSUE THREAD

**Issue by shekohex** [webb-tools/relayer#450]
## Overview

DKG should make use of the Substrate Transaction Queue instead of in-place sending transactions.

### Task Checklist

- [ ] Create transactions in-place and encode them.
- [ ] Make use of the Substrate tx queue.
- [ ] Process all extrinsic calls made to DKG and substrate through the tx queue like from [here](https://github.com/webb-tools/relayer/blob/main/crates/proposal-signing-backends/src/dkg.rs#L113)

**Comment by shekohex** [comment]
> Is there an example somewhere how this tx queue should be used?

Here is an example of using the transaction queue: https://github.com/webb-tools/relayer/blob/2b1370e592523931d7f995aa03c8bb4f29eb2547/event-watchers/substrate/src/signature_bridge_watcher.rs#L213-L240
