### ISSUE TITLE
[TASK] Deploy Relayer(s) to a new server

### ISSUE THREAD

**Issue by shekohex** [webb-tools/relayer#464]
### Overview

Relayers could run along each others without any issues on a small server, hence we could just use one medium server with 4GB RAM and 2/4 CPU cores.

### Task Checklist

- [x] Create a new server with (4GB RAM, 2 vCPU) a la `t3.medium`
- [x] Configure the server with docker and other required steps
- [x] Create different configurations directories for `prod` and `dev` environments
- [x] Create Relayers {1, 2} using the `prod` env
- [x] Create Relayers {3, 4} using the `dev` env
- [x] Update the DNS records for `webb.tools` sub-domains
- [x] Check that everything is working as usual and update the dApp team with any required changes (should be None)
- [x] Shutdown the old and unused servers.

**Comment by shekohex** [comment]
Done:

1. Relayer1 uses webbETH bridge: https://relayer1.webb.tools/api/v1/info
2. Relayer2 uses webbAlpha bridge: https://relayer2.webb.tools/api/v1/info
3. Relayer3 uses webbtTNT bridge: https://relayer3.webb.tools/api/v1/info
4. Relayer4 same as Relayer3: https://relayer4.webb.tools/api/v1/info
