### ISSUE TITLE
[TASK] Add support and Chain info for Webb Alpha Bridge

### ISSUE THREAD

**Issue by shekohex** [webb-tools/relayer#504]
### Overview

Currently Relayers does not have chain information about `Avalance Fuji (43113)`

### Reproduce the issue
1. Query the Fees information for Avalance Fuji (43113) => `1099511670889`
```
curl https://relayer2.webb.tools/api/v1/fee_info/1099511670889/0x38e7aa90c77f86747fab355eecaa0c2e4c3a463d/2000000
```
2. Relayer Responds with
```
Chain Not Found: 1099511670889
```

### Task Checklist

- [x] Branch of https://github.com/webb-tools/relayer/releases/tag/v0.5.0-rc21-alpha
- [x] Add `43113` to the [`supported_chains.toml`](https://github.com/webb-tools/relayer/blob/4908f1603d86b3d3defaaf7f096d0bdd423ba42c/crates/chains-info/supported_chains.toml#LL1C1-L1C1)
- [x] Create a new Release
- [x] Do the same for the `develop` branch.
