### ISSUE TITLE
[TASK] Use Transactional and Atomic database operations when possible

### ISSUE THREAD

**Issue by shekohex** [webb-tools/relayer#506]
### Overview

Right now, we rarely make use of the atomic updates when we are working with the database, this not something we should relay on, and instead we should use the transactional API when possible.

### The Problem

Partial writes is the root issue here, we should identify and group related operations into one atomic transaction to the database, for example, when we save the leaf and its index, then we save the last block number of that event. It happens that the relayer/user stops at the moment just before we save the last block number. This means we are going to fetch the same event again, which is not the main issue, but could lead to the bugs where we insert the same leaf again into the local merkle tree, making it producing an invalid root. Solution would be to make these two ops into one atomic transaction.

### Task Checklist

This checklist are split into two parts:

- **The first part**:
- [ ] Research and identify all the operations that we are using the database for and list them below.
- [ ] Find and identify the operations that should be grouped together into one atomic operation.

- **The second part**
- [ ] Make the required changes to the database interface to allow the above changes.
- [ ] Add more tests to make sure this works.
- [ ] Update the docs

**Comment by salman01zp** [comment]
Following are Sled DB operation 

```rust
// Event watcher DB operation
store.set_last_block_number()- // last block processed by event watcher
store.set_target_block_number() // latest block number

// Leaf watcher DB operation
store.insert_leaves()
store.insert_last_deposit_block_number()
store.store_event()

// Encrypted output watcher DB operations
store.insert_encrypted_output()
store.insert_last_deposit_block_number_for_encrypted_output()
store.store_event()

```

We can group this operation for leaf and encrypted output watcher
```rust
store.insert_leaves()
store.insert_last_deposit_block_number()
store.store_event()
```
