### ISSUE TITLE
[TASK] Fix Grafana Dashboard

### ISSUE THREAD

**Issue by shekohex** [webb-tools/relayer#507]
### Overview

Grafana Dashboard does not work as expected on the relayers endpoint and does not show any helpful mercies. 

### Task Checklist

- [ ] Make sure that Grafana Dashboard is working and reachable
- [ ] Make sure it shows all the matrices that are supported
- [ ] Make use of Grafana alerts.
