### ISSUE TITLE
[TASK] Remove the need for `TypedChainId`s in the API Endpoints

### ISSUE THREAD

**Issue by shekohex** [webb-tools/relayer#510]
### Overview

We should be consistent while working and designing our APIs, right now I see a divergence when we query something, for instance when we query the leaves cache or the encrypted outputs, we use the raw chain ids like 5 for Goerli, but when we work with fee info we use the typed chain Ids, which is not human-friendly esp for testing and debugging.

Since now we have two separate Endpoints for Fee informations, we should change the endpoints to use the raw untyped chain ids like the other endpoints we have. 

https://github.com/webb-tools/relayer/blob/008b8225a88bcb5ae4a35cb28697fbf4b9c92c02/crates/relayer-handlers/src/lib.rs#L200-L237

### Task Checklist

- [x] Change EVM Fee info to accept the `chain_id` instead of `typed_chain_id`
- [x] Change Substrate Fee info to accept the `chain_id` instead of `typed_chain_id`
- [x] Update tests
- [x] Update docs (README, docs website, ..etc)
- [ ] Notify the dApp team with these breaking changes before we deploy the new update.

**Comment by Nutomic** [comment]
FYI @drewstone was the one who suggested using `TypedChainId` for fee endpoints.

https://github.com/webb-tools/relayer/pull/325#discussion_r1068950691

**Comment by shekohex** [comment]
> FYI @drewstone was the one who suggested using `TypedChainId` for fee endpoints.
> 
> [#325 (comment)](https://github.com/webb-tools/relayer/pull/325#discussion_r1068950691)

This was okay, at least while we only had EVM Fees, but now we have different modules/endpoints for each, no reason to have a typed chain id while the endpoint itself has the part `evm` or `substrate` in it.
