### ISSUE TITLE
[TASK] Embed Relayer version, git commit/rev into relayer binary for `/api/v1/info`

### ISSUE THREAD

**Issue by shekohex** [webb-tools/relayer#512]
### Overview

It is hard to tell what version or what git commit this relayer is currently running? which makes me think we should embed these information in the result binary at compile-time so that we can return these info in the `/api/v1/info` endpoint. This will be super useful in the future (for now here is a tease for future usage of this: `relayerup clone https://relayer1.webb.tools` :shushing_face: )

### Example

By default, most of the information we add in Cargo.toml are already exposed as `CARGO_*` env during compile time, for example:

```rust
let version = env!("CARGO_PKG_VERSION");
```
For more, you can read about it [here](https://doc.rust-lang.org/cargo/reference/environment-variables.html#environment-variables-cargo-sets-for-crates).

- **What about git commit and git release name?**
In our build.rs we can do something like the following:

```rust
println!("cargo:rustc-env=GIT_BRANCH={}", get_git_branch()));
```

This will tell cargo to set this env for us, so that we can do the following in our main program:

```rust
let branch = env!("GIT_BRANCH");
```

> There a crate that actually helps in doing all of this [`build-data`](https://docs.rs/crate/build-data/0.1.4)

### Expected Response

Utilizing this in Our CI/CD, and reading that in our code, we want to have something like the following in our `/api/v1/info`

```json
{
  "evm": {},
  "substrate": {},
  "experimental": {},
  "features": {},
  "assets": {},
  "build": {
    "version": "0.5.0-rc22-alpha",
    "commit": "ef4e899",
    "timestamp": "2023-05-12T13:42:54Z"
  }
}
```
> NOTE: the `build.timestamp` uses `SOURCE_TIMESTAMP` env, to help making this a [`Reproducible build`](https://reproducible-builds.org/docs/timestamps/)

### Task Checklist

- [ ] Make use of `build-data` crate
- [ ] Embed the required information in the `build.rs`
- [ ] Add a CI check in the release workflow that checks that version inside the `Cargo.toml` matches the version of the tag relesae.
- [ ] Update the `/api/v1/info` endpoint.
- [ ] Update the docs and tests if required.
