### ISSUE TITLE
[TASK] Investigate why we call `eth_getTransactionByHash` RPC so many times

### ISSUE THREAD

**Issue by shekohex** [webb-tools/relayer#528]
### Overview

Using Infura Stats, we noticed that we call `eth_getTransactionByHash` a lot, which is indication that there is a room left here to improve the number of RPCs we send.
<img width="1635" alt="image" src="https://github.com/webb-tools/relayer/assets/14620076/a2631e30-3c67-432d-b7df-2bb2cc4303bf">

### Task Checklist

- [ ] Explore a way to get metrics from ethers-rs (using the tracing logs for example)
- [ ] Propose a way to lower the number of RPCs
- [ ] Add tests (if required)

**Comment by salman01zp** [comment]
While processing the EVM Tx queue [here](https://github.com/webb-tools/relayer/blob/develop/crates/tx-queue/src/evm/evm_tx_queue.rs#L155) every `send_transaction` method calls `get_transaction` to obtain the pending state of the transaction using a polling mechanism with some interval
For more details on PendingTransaction refer [here](https://docs.rs/ethers-providers/2.0.7/src/ethers_providers/toolbox/pending_transaction.rs.html#154).


Maybe we can try increasing polling interval [here](https://docs.rs/ethers-providers/2.0.7/src/ethers_providers/rpc/provider.rs.html#101). Default is 7 sec
Will try running some tests

**Comment by salman01zp** [comment]
@shekohex can you share the count log for the `eth_getTransactionByHash` method for each chain?  I think this count is related to block-producing time.

The default polling interval is 7 sec, we can set it to `block_time/2`
```rust
let mut provider = Provider::new(retry_client);
// Todo set interval to `block time / 2`
provider.set_interval(Duration::from_secs(interval));
```

**Comment by salman01zp** [comment]
Yeah, using WebSockets does reduce RPC usage. We can use ws-provider just for tx-queue but there will be cons if the connection is closed and subscriptions are dropped.

something like 
```rust
pub enum WebbProviders {
    Http(Provider<Http>),
    Ws(Provider<Ws>)
}
```

**Comment by shekohex** [comment]
> Yeah, using WebSockets does reduce RPC usage. We can use ws-provider just for tx-queue but there will be cons if the connection is closed and subscriptions are dropped.

The connection should be restored if we did return an error in the tx queue, since the queue is running in a retry task. Also, I do assume we can wrap the client in a retry client, so it will retry to reconnect for example.
