### ISSUE TITLE
[TASK] Expose HTTP GET API for inspecting the status of a transaction in the TxQueue

### ISSUE THREAD

**Issue by shekohex** [webb-tools/relayer#535]
### Overview

We need a simple GET API that we can utilize to query a status of tx in the txqueue by using a item key.

### Task Checklist

- [ ] Expose GET `/api/v1/tx/evm/<CHAIN_ID>/<ITEM_KEY>`
- [ ] Expose GET `/api/v1/tx/substrate/<CHAIN_ID>/<ITEM_KEY>`
- [ ] Response should return the following:
  - [ ] Not Found 404
  - [ ] `{ "itemkey": "0x123....", "status": "Pending" }`
  - [ ] `{ "itemkey": "0x123....", "status": "Dropped" }`
  - [ ] `{ "itemkey": "0x123....", "status": "Failed", "reason": "...." }`
  - [ ] `{ "itemkey": "0x123....", "status": "Finalized/Minted" }`

**Comment by drewstone** [comment]
`"itemkey"`
