### ISSUE TITLE
[TASK] Handle `ResourceIdUpdate` Proposal

### ISSUE THREAD

**Issue by shekohex** [webb-tools/relayer#542]
### Overview

In Our protocol we can add new handlers overtime on the same chain that all connected to one Signature Bridge contract. Adding a new Resource to the Signature bridge is handled through our proposal system using the [webb_proposals](https://docs.rs/webb-proposals/latest/webb_proposals/index.html)::[evm](https://docs.rs/webb-proposals/latest/webb_proposals/evm/index.html)::[ResourceIdUpdateProposal](https://docs.rs/webb-proposals/latest/webb_proposals/evm/struct.ResourceIdUpdateProposal.html) and it is treated differently since the proposal is executed on the Signature Bridge contract itself not on `IExecutor` handler.

### Task Checklist

- [x] Check if the signed proposal's function signature matches `adminSetResourceWithSignature(bytes32,bytes4,uint32,bytes32,address,bytes)`
- [x] If so, Construct the call to [`adminSetResourceWithSignature`](https://github.com/webb-tools/protocol-solidity/blob/f326f21689bbe2b7fd644e6b6f9953de0122e389/packages/contracts/contracts/SignatureBridge.sol#LL60C11-L60C40)
- [x] Add test for adding a new handler to the signature bridge contract.
- [ ] Update the docs (if needed)
