### ISSUE TITLE
[TASK] Optmize Substrate Connections

### ISSUE THREAD

**Issue by shekohex** [webb-tools/relayer#579]
### Overview
Recently, we found a bug that spams (opens a lot of) connections to the tangle archival nodes, this may be due to a lot of clients that gets created instead of cached. we found it easily identifiable from the logging here:
 https://github.com/webb-tools/relayer/blob/f42ec552697faca1f6bd3b5749ce26c11d702d66/crates/event-watcher-traits/src/substrate/event_watcher.rs#L159-L171 which was introduced through this PR #522 

Every call to [`ctx.substrate_provider`](https://github.com/webb-tools/relayer/blob/f42ec552697faca1f6bd3b5749ce26c11d702d66/crates/relayer-context/src/lib.rs#L222) actually creates a new connection (even for the same chain id) which is a waste of resources, what we should do instead is to cache the RPC clients in a hashmap so that we can reuse them across different clients. That is exactly we did [way back](https://github.com/webb-tools/relayer/commit/17dc90c56c1ae8ba122b91abe505f2370eab37bc) for EVM Providers.

### Task Checklist

- [x] Create a shared RPC Client and store it in `Arc<HashMap<types::U256, Arc<RpcClient>>>`
- [x] Construct the RPC Clients during the `RelayerContext::new` call (notice that creating the clients does not actually connect)
- [x] Whenever we call `RelayerContext::substrate_provider` method, we create a new `OnlineClient` from the shared `Arc<RpcClient>` we cached.
- [x] if this failed, calling this again with a same client will reuse the connection.
- [x] Can we use `HttpClient` as RPC Client? if yes, maybe that is a better option as they are stateless.
- [ ] (_optional_) While constructing the RpcClient, please add `User-Agent` header to `webb-relayer/<version> <build-commit>` so that we can see these in the Graphana logs/UI.

### References

1. Creating a custom RPC Client: https://github.com/paritytech/subxt/blob/c8462defabad10a2c09f945737731e7259f809dd/subxt/src/backend/rpc/rpc_client.rs#L240-L253
2. Using the created RPC Client to create an OnlineClient: https://github.com/paritytech/subxt/blob/059723e4313d91e8ca0bcd84b0dd7dd66686ca50/subxt/src/client/online_client.rs#L86

**Comment by salman01zp** [comment]
Since we use subscriptions, I don't think we can use HttpClient Also why not cache just `OnlineClient`

**Comment by salman01zp** [comment]
Creating `RpcClient` wrapper for something that `impl RpcClientT` is not possible in the current version of subxt, since its `new` method is private.
This will be available in the next release
https://github.com/paritytech/subxt/blob/c8462defabad10a2c09f945737731e7259f809dd/subxt/src/backend/rpc/rpc_client.rs#L23-#L35

Most likely we will have to create `jsonrpsee::client` and cache this client and then create a new OnlineClient from cached
