### ISSUE TITLE
[SPEC] New API methods for querying relayer / anchor state

### ISSUE THREAD

**Issue by drewstone** [webb-tools/relayer#58]
The goal is to expose new API endpoints on the relayer for clients to query data about the smart contract protocol. We will want to define a few new API endpoints and different data points to query from the Solidity smart contracts.

## API endpoints
- `/api/v1/balances`
- `/api/v1/transactions`
- `/api/v1/history`

## Queries
- Querying the balance of the anchor
- Querying the balance of the token wrappers
- Querying the # of deposits / withdrawals (using historical data)

## Resources
- Adding new API methods will be in `main.rs` such as https://github.com/webb-tools/relayer/blob/ec6505776b61c96a1f9e91e7cfcc6bb7b38b930b/src/main.rs#L179.
- Adding new handlers for the API methods will be in `handler.rs` such as https://github.com/webb-tools/relayer/blob/6b5733151f6f3e38f0c3b6ccba33f13a32cfef1f/src/handler.rs#L107

## Implementation
When the APIs are called, you will want to parse the configuration file and extract the contract addresses that are being called/queried in order to fetch data from them. This will require using the generated contract interfaces and making the correct queries to them such as getting balances or polling the contracts for their latest events.

### Tasks

- [ ] Documentation or API reference guide
- [ ] Tests for querying API endpoints
- [ ] Tests for leaf watching / querying on Mixer, Anchor, VAnchor

### Questions

- How can the relayer provide data to update the wrapper classes easily?
