### ISSUE TITLE
[CHECKLIST] Relayer registry / onchain configuration + Bridge Registry

### ISSUE THREAD

**Issue by drewstone** [webb-tools/relayer#581]
# Overview
A potential new idea to make relayer operations more seamless. Since relayers have EVM keys we could consider having a precompile for this.

### Relayer registry
The first thing would be a relayer registry where relayers _**opt-in**_ to the bridges they want to relay for, say index 1,2,3. Then every time they shutdown and spin back up, they can easily check which bridges they've opted-in to relay for and quickly spin up with minimal configuration.

This would obviously benefit from a UI but could also be possibly implemented as a relayer CLI.

### Bridge registry
The purpose of this bridge registry is to minimize as much configuration for external relayers. We should continue to leverage this and figure out how to make relayer management easy and seamless.

## Checklist
- [ ] Implement relayer registry pallet (where relayers put their config)
- [ ] Implement relayer registry precompile
- [ ] Relayer CLI to expose getters/setters for pallet
- [ ] Integration where there is less configuration on relayer
