### ISSUE TITLE
[CHECKLIST] Event Watchers for MASP

### ISSUE THREAD

**Issue by dev0x1** [webb-tools/relayer#585]
Relayer needs to have support for the following MASP events:
- [ ] Event related to the updation of roots of MASPTree
- [ ] Event related to the updation of roots of SpentTree
- [ ] Event related to the updation of roots of UnspentTree
- [ ] Event related to all supported governance proposal
- [ ] Event related to all supported reward transactions
- [ ] Batch insertion of all supported transactions
